# Generated by Django 4.2.4 on 2023-08-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Ник')),
                ('email', models.EmailField(max_length=10, verbose_name='email')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Создано')),
                ('age', models.IntegerField(max_length=100, verbose_name='Возраст')),
                ('wallet_adress', models.CharField(max_length=12, verbose_name='Кошелек')),
            ],
        ),
    ]
