# Generated by Django 4.2.4 on 2023-08-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Создано')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('wallet_adress', models.CharField(max_length=12, verbose_name='Кошелек')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
