# Generated by Django 4.2.4 on 2023-08-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_delete_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
