# Generated by Django 4.2.4 on 2023-08-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.CharField(blank=True, default=0, max_length=255, null=True, verbose_name='Баланс'),
        ),
    ]
