# Generated by Django 4.2.4 on 2023-09-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.CharField(default=0, max_length=255, verbose_name='Баланс'),
        ),
    ]
