# Generated by Django 4.2.4 on 2023-08-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_managers_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_adress',
            field=models.CharField(max_length=12, verbose_name='Кошелек'),
        ),
    ]
