# Generated by Django 4.2.4 on 2023-08-29 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_wallet_adress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryTransfer',
        ),
    ]
